options:
  debug: false
  #战斗系统
  fight:
    enable: true
    #原版抛射物伤害是否会按攻击者射箭时的属性计算 而非射中时的属性
    projectile-cache-data: true
    #是否进行非玩家实体间的战斗计算
    eve-fight-cal: false
    vanilla-armor: true
    #若没有这些权限，则攻击时运行默认的 attack 战斗组
    #当攻击者拥有这个权限时，攻击时将运行 class-a-attack 战斗组
    #      as.class.a: class-a-attack
    # as.class.b: class-b-attack
    attack-fight: { }
    #是否计算 MM 的 damage 机制的伤害
    mm-damage-cal: false
    #是否计算 SkillAPI 的 damage 机制的伤害
    skill-api-damage-cal: false
